# 集群名称
cluster.name: elasticsearch-cluster
# 节点名称
node.name: elasticsearch-master
# 是否可以成为master节点
node.master: true
# 是否允许该节点存储数据,默认开启
node.data: true
# 网络绑定
network.host: 0.0.0.0
# 设置对外服务的http端口
http.port: 9200
# 设置节点间交互的tcp端口
transport.port: 9300
# 集群发现
#discovery.seed_hosts:
#  - elasticsearch-master
#  - elasticsearch-slave1
#  - elasticsearch-slave2
# 手动指定可以成为 mater 的所有节点的 name 或者 ip，这些配置将会在第一次选举中进行计算
#cluster.initial_master_nodes:
#  - elasticsearch-master
# 支持跨域访问
http.cors.enabled: true
http.cors.allow-origin: "*"

# 安全认证
#xpack.security.enabled: false
#xpack.security.enabled: true
#xpack.security.transport.ssl.enabled: true
#http.cors.allow-headers: "Authorization"
#设置密码后要添加这个选项 追的配置
#xpack.security.transport.ssl.keystore.type: PKCS12
#xpack.security.transport.ssl.verification_mode: certificate
#xpack.security.transport.ssl.keystore.path: elastic-stack-ca.p12
#xpack.security.transport.ssl.truststore.path: elastic-stack-ca.p12
#xpack.security.transport.ssl.truststore.type: PKCS12