version: "3"
services:
  # 设置 mysql_master 服务
  mysql_master:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql-master-${MYSQL_VERSION}
    environment:
      - TZ=Asia/Shanghai
      # 配置mysql root 账号密码
      - MYSQL_ROOT_PASSWORD=Secret2017~
    command:
      --default-authentication-plugin=mysql_native_password
    ports:
      - "33061:3306"
    volumes:
      - ./conf/master/my.cnf:/etc/mysql/my.cnf
      - ./conf/master/data:/var/lib/mysql
#      - ./conf/master/files:/var/lib/mysql-files
    restart: "always"
    networks:
      - mysql-net
    ulimits:  #ulimits指定容器的 ulimits 限制值。例如，指定最大进程数为 65535，指定文件句柄数为 20000（软限制，应用可以随时修改，不能超过硬限制） 和 40000（系统硬限制，只能 root 用户提高)
      nproc: 65535
      nofile:
        soft: 100000
        hard: 200000
  # 设置 mysql_slave 服务
  mysql_slave:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql-slave-${MYSQL_VERSION}
    environment:
      - TZ=Asia/Shanghai
      # 配置mysql root 账号密码
      - MYSQL_ROOT_PASSWORD=Secret2017~
    command:
      --default-authentication-plugin=mysql_native_password
    ports:
      - "33062:3306"
    volumes:
      - ./conf/slave/my.cnf:/etc/mysql/my.cnf
      - ./conf/slave/data:/var/lib/mysql
#      - ./conf/slave/files:/var/lib/mysql-files
    restart: "always"
    networks:
      - mysql-net
    ulimits:
      nproc: 65535
      nofile:
        soft: 100000
        hard: 200000
networks:
  mysql-net:
    driver: bridge