version: "3.8"
services:
  elasticsearch:
    image: elasticsearch:${ELK_VERSION}
    container_name: elasticsearch-${ELK_VERSION}
    environment:
      - TZ=Asia/Shanghai
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "127.0.0.1:9300:9300"
    restart: "always"
    volumes:
      #- /etc/localtime:/etc/localtime
      #- /etc/timezone:/etc/timezone
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data/:/usr/share/elasticsearch/data/
      - ./elasticsearch/logs/:/usr/share/elasticsearch/logs/
    networks:
      - elk-net
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:${ELK_VERSION}
    container_name: kibana-${ELK_VERSION}
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
#      - elasticsearch.hosts=http://localhost:9200 #配置文件中写了这就不要了，这里要是进去就不能选数据源了
      - "TZ=Asia/Shanghai"
    volumes:
      #- /etc/localtime:/etc/localtime
      #- /etc/timezone:/etc/timezone
      - ./kibana/config/:/usr/share/kibana/config/
    networks:
      - elk-net
    restart: "always"
    ulimits:
      memlock:
        soft: -1
        hard: -1
networks:
  elk-net:
    driver: bridge
