version: "3.8"
services:
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION}
    container_name: jaeger-${JAEGER_VERSION}
    environment:
      - TZ=Asia/Shanghai
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    restart: "always"
    networks:
      - jaeger-net
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    network_mode:  host
networks:
  jaeger-net:
    driver: bridge
